language: python
cache: pip
sudo: false

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

env:
  - DJANGO=1.11
  - DJANGO=2.0

install:
  - pip install jinja2 mako tornado six coverage nose
  - pip install django==$DJANGO

matrix:
    fast_finish: true
    exclude:
      - { python: "2.7", env: DJANGO=2.0 }

#    allow_failures:
#      - env: DJANGO=master

script: make coverage

after_success:
  - codecov
