language: python
sudo: false
python:
  - "2.7"
  - "3.6"
cache:
  directories:
    - .cache/pip/
    - $HOME/.cache/pip

install:
- |
  pip install django==$DJANGO_VERSION
  pip install -r requirements.txt --use-mirrors
  python setup.py develop

script: "nosetests -w pypugjs/testsuite/ -v"
env:
  matrix:
    - DJANGO_VERSION=1.9
    - DJANGO_VERSION=1.10
    - DJANGO_VERSION=1.11
    - DJANGO_VERSION=2.0
    allow_failures:
      - python: "2.7"
